# github.com/greshake/i3status-rust
theme = "solarized-dark"
icons = "none"

[[block]]
block = "xrandr"
interval = 120

[[block]]
block = "time"
format = "%Y-%m-%d %T [%A]"
timezone = "Asia/Shanghai"
locale = "zh_CN"
interval = 1
